"""Integration test for the MCP shell-exec end-to-end path.

This test proves the full round-trip:
  browser-equivalent (httpx) → FastAPI → MCP subprocess (real server.py) → FastAPI → DB

Design:
  - Uses the *real* shell-exec server.py subprocess — NOT a mock.
    subprocess_manager spawns `sys.executable <repo>/mcp-servers/shell-exec/server.py`
    via a test-local mcp.yaml written to a tmp_path, so no container paths are required
    and the test is host-runnable.

  - Spins up a *throwaway* Postgres schema (same pattern as auth/tests/test_integration.py
    and engagements/tests/test_integration.py) so the test never touches the dev/prod tables
    and cleans up on teardown.

  - Builds a minimal FastAPI app with a custom lifespan that (a) loads the registry from
    the test mcp.yaml, (b) calls subprocess_manager.startup() to spawn the real subprocess,
    and (c) calls subprocess_manager.shutdown() on exit.  Auth + engagements + mcp routers
    are all included so login, engagement creation, and tool-run all work.

  - get_db is overridden to use the throwaway-schema session factory, so the lifespan's
    admin bootstrap and all router DB calls land in the isolated schema.

  - Subprocess manager module-level state (_handles, _registry) is reset in teardown so
    successive test runs don't inherit a stale running handle.

Marked ``integration``: excluded from the default ``make test-backend`` run; use
``make test-integration`` or:
  cd backend && uv run pytest -m integration app/features/mcp/tests/test_mcp_integration.py -v

Prerequisites: Postgres reachable at the default compose DSN or ADEPTUS_TEST_DATABASE_URL.
The test skips automatically (pytest.skip) when no Postgres is available.
"""

from __future__ import annotations

import os
import sys
import uuid
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager
from pathlib import Path

import pytest
import pytest_asyncio
from argon2 import PasswordHasher
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

from app.core.config import get_settings
from app.core.db import Base, get_db, get_engine, get_sessionmaker
from app.core.errors import register_error_handlers
from app.features.auth import models as auth_models  # noqa: F401 — register ORM metadata
from app.features.auth import repository as auth_repo
from app.features.auth.router import router as auth_router
from app.features.engagements import models as eng_models  # noqa: F401 — register ORM metadata
from app.features.engagements import repository as eng_repo
from app.features.engagements.router import router as engagements_router
from app.features.mcp import models as mcp_models  # noqa: F401 — register ORM metadata
from app.features.mcp import registry as mcp_registry
from app.features.mcp import subprocess_manager
from app.features.mcp.models import ToolRun
from app.features.mcp.router import router as mcp_router

pytestmark = pytest.mark.integration

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_DEFAULT_DSN = "postgresql+asyncpg://adeptus:adeptus@localhost:5432/adeptus"
_MEMBER_PW = "correcthorse"
_MEMBER_HASH = PasswordHasher().hash(_MEMBER_PW)

# Resolve the server.py path from this test file's location.
# test file:  backend/app/features/mcp/tests/test_mcp_integration.py
# server.py:  mcp-servers/shell-exec/server.py  (5 parents up from tests/, then down)
#
# Layout:  <repo-root>/
#   backend/app/features/mcp/tests/   ← this file
#   mcp-servers/shell-exec/server.py  ← target
#
# Path: this_file → tests/ → mcp/ → features/ → app/ → backend/ → repo-root
_REPO_ROOT = Path(__file__).parents[5]
_SHELL_EXEC_SERVER = _REPO_ROOT / "mcp-servers" / "shell-exec" / "server.py"


def _dsn() -> str:
    return os.environ.get("ADEPTUS_TEST_DATABASE_URL") or _DEFAULT_DSN


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def test_mcp_config(tmp_path: Path) -> Path:
    """Write a test-local mcp.yaml that points to the real server.py on the host.

    Uses sys.executable as the interpreter so the correct venv Python runs the
    server (important when the tests run inside a virtualenv).  The path to
    server.py is resolved absolutely from the repo root so the test is
    cwd-independent.
    """
    if not _SHELL_EXEC_SERVER.exists():
        pytest.skip(f"shell-exec server.py not found at {_SHELL_EXEC_SERVER}")

    config_content = f"""\
# Test-only MCP config generated by test_mcp_integration.py.
# Uses sys.executable + absolute path so the test runs correctly on the host
# without the container paths (/mcp-servers/...) that the compose stack uses.
servers:
  - name: shell-exec
    command: {sys.executable}
    args:
      - {_SHELL_EXEC_SERVER}
    tools:
      - name: run_command
        weight: light
        capability_flags:
          - shell-exec
          - filesystem-write
"""
    config_path = tmp_path / "mcp_test.yaml"
    config_path.write_text(config_content)
    return config_path


@pytest_asyncio.fixture
async def pg_schema_factory(
    monkeypatch: pytest.MonkeyPatch,
) -> AsyncGenerator[async_sessionmaker[AsyncSession], None]:
    """Session factory scoped to a throwaway Postgres schema.

    Mirrors the pattern used by auth/tests/test_integration.py and
    engagements/tests/test_integration.py.  Skips if Postgres is not reachable.
    """
    # Point settings at the integration DB for this test.
    monkeypatch.setenv("DATABASE_URL", _dsn())
    monkeypatch.setenv("ADEPTUS_ADMIN_USER", "admin_it")
    monkeypatch.setenv(
        "ADEPTUS_ADMIN_PASSWORD_HASH",
        "$argon2id$v=19$m=65536,t=3,p=4$dGVzdHNhbHQ$hashhashhashhashhashhashhashhashhashhashhas",
    )
    get_settings.cache_clear()
    get_engine.cache_clear()
    get_sessionmaker.cache_clear()

    schema = f"mcp_it_{uuid.uuid4().hex[:12]}"
    admin_engine = create_async_engine(_dsn(), isolation_level="AUTOCOMMIT")
    try:
        async with admin_engine.connect() as conn:
            await conn.execute(text(f'CREATE SCHEMA "{schema}"'))
    except Exception as exc:  # noqa: BLE001 — any failure means Postgres not available
        await admin_engine.dispose()
        pytest.skip(f"Postgres not available for integration tests: {exc}")

    engine = create_async_engine(
        _dsn(),
        connect_args={"server_settings": {"search_path": schema}},
    )
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    factory = async_sessionmaker(engine, expire_on_commit=False, class_=AsyncSession)
    try:
        yield factory
    finally:
        await engine.dispose()
        async with admin_engine.connect() as conn:
            await conn.execute(text(f'DROP SCHEMA "{schema}" CASCADE'))
        await admin_engine.dispose()
        # Clear lru_cache so the next test starts fresh.
        get_settings.cache_clear()
        get_engine.cache_clear()
        get_sessionmaker.cache_clear()


def _make_mcp_app(
    factory: async_sessionmaker[AsyncSession],
    config_path: Path,
) -> FastAPI:
    """Build a minimal FastAPI app with auth + engagements + mcp routers.

    Uses a custom lifespan that:
      1. Loads the registry from the test mcp.yaml (real server.py on host).
      2. Calls subprocess_manager.startup() to spawn the real subprocess.
      3. Calls subprocess_manager.shutdown() on exit.

    get_db is overridden to use the throwaway-schema session factory so all
    DB calls from the routers (and the lifespan's admin bootstrap) land in the
    isolated test schema.
    """

    @asynccontextmanager
    async def test_lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
        # Reset any stale subprocess_manager state from previous tests.
        mcp_registry._reset_registry()  # noqa: SLF001
        subprocess_manager._reset_manager()  # noqa: SLF001

        # Load the test-local registry and spawn the real shell-exec subprocess.
        mcp_registry.load_registry(config_path=str(config_path))
        await subprocess_manager.startup()

        yield

        # Terminate the subprocess on teardown.
        await subprocess_manager.shutdown()
        mcp_registry._reset_registry()  # noqa: SLF001
        subprocess_manager._reset_manager()  # noqa: SLF001

    app = FastAPI(lifespan=test_lifespan)
    register_error_handlers(app)
    app.include_router(auth_router)
    app.include_router(engagements_router)
    app.include_router(mcp_router)

    async def override_get_db() -> AsyncGenerator[AsyncSession, None]:
        async with factory() as session:
            yield session

    app.dependency_overrides[get_db] = override_get_db
    return app


# ---------------------------------------------------------------------------
# Integration tests
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_tool_run_echo_hello_end_to_end(
    pg_schema_factory: async_sessionmaker[AsyncSession],
    test_mcp_config: Path,
) -> None:
    """Full round-trip: login → create engagement → POST /tool-runs → assert result + DB row.

    Steps:
      1. Seed a member user directly via the repository.
      2. Create an engagement and add the user as explicit owner (no admin bypass — §4).
      3. Log in via POST /api/v1/auth/login.
      4. POST /api/v1/tool-runs with command="echo hello".
      5. Assert HTTP 200, exit_code==0, stdout=="hello\\n".
      6. Assert a tool_runs row exists in the DB with the correct fields.
    """
    # ---- step 1: seed a member user ----------------------------------------
    async with pg_schema_factory() as session:
        member = await auth_repo.create_user(
            session, username="member_user", password_hash=_MEMBER_HASH, role="user"
        )
        await session.commit()
        member_id = member.id

    # ---- step 2: create engagement with member as owner --------------------
    async with pg_schema_factory() as session:
        engagement = await eng_repo.create_engagement(
            session,
            name="MCP Integration Test Engagement",
            scope="10.0.0.0/8",
            client_info=None,
            owner_id=member_id,  # type: ignore[arg-type]
        )
        await session.commit()
        engagement_id = engagement.id

    # ---- build app and run the lifespan (spawns shell-exec subprocess) -----
    app = _make_mcp_app(pg_schema_factory, test_mcp_config)

    async with app.router.lifespan_context(app):
        async with AsyncClient(transport=ASGITransport(app=app), base_url="https://test") as client:
            # ---- step 3: login -----------------------------------------------
            login_resp = await client.post(
                "/api/v1/auth/login",
                json={"username": "member_user", "password": _MEMBER_PW},
            )
            assert login_resp.status_code == 200, f"Login failed: {login_resp.text}"
            assert get_settings().SESSION_COOKIE_NAME in client.cookies

            # ---- step 4: POST /api/v1/tool-runs ------------------------------
            tool_run_resp = await client.post(
                "/api/v1/tool-runs",
                json={
                    "engagement_id": str(engagement_id),
                    "server_name": "shell-exec",
                    "tool_name": "run_command",
                    "args": {"command": "echo hello"},
                },
            )
            assert tool_run_resp.status_code == 200, (
                f"tool-run failed ({tool_run_resp.status_code}): {tool_run_resp.text}"
            )

            # ---- step 5: assert response fields ------------------------------
            body = tool_run_resp.json()
            assert body["exit_code"] == 0, f"Expected exit_code 0, got {body['exit_code']}"
            assert body["stdout"] == "hello\n", (
                f"Expected stdout 'hello\\n', got {body['stdout']!r}"
            )
            assert body["server_name"] == "shell-exec"
            assert body["tool_name"] == "run_command"
            assert body["engagement_id"] == str(engagement_id)

            tool_run_id = body["tool_run_id"]

    # ---- step 6: assert tool_runs row in the DB ----------------------------
    # Query outside the lifespan context (subprocess already shut down) but the
    # DB schema is still accessible until the pg_schema_factory teardown.
    async with pg_schema_factory() as session:
        result = await session.execute(select(ToolRun).where(ToolRun.id == uuid.UUID(tool_run_id)))
        row = result.scalar_one_or_none()

    assert row is not None, f"No tool_runs row found for id={tool_run_id}"
    assert row.exit_code == 0
    assert row.stdout == "hello\n"
    assert row.engagement_id == engagement_id
    assert row.server_name == "shell-exec"
    assert row.tool_name == "run_command"
    assert row.finished_at is not None, "finished_at should be set after a completed run"
