"""slice-01: engagements and engagement_members tables

Revision ID: 1eb283db46ca
Revises: 0a1f3f9f803c
Create Date: 2026-05-30 18:31:05.486402

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1eb283db46ca"
down_revision: str | Sequence[str] | None = "0a1f3f9f803c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engagements",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("client_info", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=16), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name="ck_engagements_status"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_engagements_status", "engagements", ["status"], unique=False)
    op.create_table(
        "engagement_members",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), server_default=sa.text("'member'"), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("role IN ('owner', 'member')", name="ck_engagement_members_role"),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("engagement_id", "user_id"),
    )
    op.create_index(
        "ix_engagement_members_user_id", "engagement_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # Postgres trigger to keep engagements.updated_at current on every UPDATE.
    # The ORM onupdate= fires only on explicit ORM UPDATEs; this trigger ensures
    # the column stays accurate even for direct SQL updates or future patches.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_engagements_updated_at()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_engagements_updated_at
        BEFORE UPDATE ON engagements
        FOR EACH ROW EXECUTE FUNCTION set_engagements_updated_at();
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_engagements_updated_at ON engagements;")
    op.execute("DROP FUNCTION IF EXISTS set_engagements_updated_at();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_engagement_members_user_id", table_name="engagement_members")
    op.drop_table("engagement_members")
    op.drop_index("ix_engagements_status", table_name="engagements")
    op.drop_table("engagements")
    # ### end Alembic commands ###
