"""slice-06: add paused column to engagements

Revision ID: 242bbe6579ff
Revises: 9302c6e41ee2
Create Date: 2026-06-03 17:26:14.104374

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "242bbe6579ff"
down_revision: str | Sequence[str] | None = "9302c6e41ee2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "engagements",
        sa.Column("paused", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("engagements", "paused")
    # ### end Alembic commands ###
