"""slice-09: graph_user_undo_stack personal undo stack

Revision ID: 30cbe97a54f8
Revises: f00f87bef9f6
Create Date: 2026-06-03 23:40:32.569833

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30cbe97a54f8"
down_revision: str | Sequence[str] | None = "f00f87bef9f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_user_undo_stack",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("op_type", sa.String(length=16), nullable=False),
        sa.Column("entity_kind", sa.String(length=8), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("target_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("summary", sa.String(length=256), nullable=False),
        sa.Column("undone", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "entity_kind IN ('node', 'edge')", name="ck_graph_user_undo_stack_entity_kind"
        ),
        sa.CheckConstraint(
            "op_type IN ('create_node', 'update_node', 'delete_node', "
            "'create_edge', 'delete_edge')",
            name="ck_graph_user_undo_stack_op_type",
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_graph_user_undo_stack_owner",
        "graph_user_undo_stack",
        ["engagement_id", "user_id", "undone", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_graph_user_undo_stack_owner", table_name="graph_user_undo_stack")
    op.drop_table("graph_user_undo_stack")
    # ### end Alembic commands ###
