"""slice-10: audit_entries and audit_chain_head

Revision ID: 787fa8ddf114
Revises: 30cbe97a54f8
Create Date: 2026-06-05 01:57:08.464648

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "787fa8ddf114"
down_revision: str | Sequence[str] | None = "30cbe97a54f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_chain_head",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("last_seq", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "head_hash",
            sa.CHAR(length=64),
            server_default=sa.text(
                "'0000000000000000000000000000000000000000000000000000000000000000'"
            ),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name="ck_audit_chain_head_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_entries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("engagement_id", sa.UUID(), nullable=True),
        sa.Column("target_type", sa.String(length=32), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("self_approved", sa.Boolean(), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("prev_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("entry_hash", sa.CHAR(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('login', 'logout', 'login_failed', 'tool_run', "
            "'tool_run_completed', 'graph_node_created', 'graph_node_updated', "
            "'graph_node_deleted', 'graph_edge_created', 'graph_edge_deleted', "
            "'approval_granted', 'approval_rejected', 'ai_call')",
            name="ck_audit_entries_action",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_hash", name="uq_audit_entries_entry_hash"),
        sa.UniqueConstraint("seq", name="uq_audit_entries_seq"),
    )
    op.create_index(
        "ix_audit_entries_action_seq",
        "audit_entries",
        ["action", sa.literal_column("seq DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_entries_engagement_seq",
        "audit_entries",
        ["engagement_id", sa.literal_column("seq DESC")],
        unique=False,
    )
    # ### end Alembic commands ###

    # Seed the single chain-head row (id=1, last_seq=0, head_hash=64 zeros == genesis).
    # The append path SELECT ... FOR UPDATEs this row to serialize appends; it must
    # exist for the first append. (append_entry self-seeds as a fallback, but the
    # authoritative head is created here.)
    op.execute(
        "INSERT INTO audit_chain_head (id, last_seq, head_hash) VALUES (1, 0, '" + ("0" * 64) + "')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_entries_engagement_seq", table_name="audit_entries")
    op.drop_index("ix_audit_entries_action_seq", table_name="audit_entries")
    op.drop_table("audit_entries")
    op.drop_table("audit_chain_head")
    # ### end Alembic commands ###
