"""slice-02: add privacy_mode to engagements

Revision ID: 7fb8ac9e4b1e
Revises: 1eb283db46ca
Create Date: 2026-05-31 18:09:20.711761

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7fb8ac9e4b1e"
down_revision: str | Sequence[str] | None = "1eb283db46ca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "engagements",
        sa.Column(
            "privacy_mode",
            sa.String(length=16),
            server_default=sa.text("'local_only'"),
            nullable=False,
        ),
    )
    # Autogenerate does not detect CheckConstraints — added manually to match models.py.
    op.create_check_constraint(
        "ck_engagements_privacy_mode",
        "engagements",
        "privacy_mode IN ('local_only', 'cloud_enabled')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_engagements_privacy_mode", "engagements", type_="check")
    op.drop_column("engagements", "privacy_mode")
    # ### end Alembic commands ###
