"""slice-12: chat_messages.graph_context

Revision ID: 942a643de71f
Revises: ca422a5de29a
Create Date: 2026-06-05 14:00:41.558343

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "942a643de71f"
down_revision: str | Sequence[str] | None = "ca422a5de29a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages",
        sa.Column(
            "graph_context",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "graph_context")
    # ### end Alembic commands ###
