"""slice-15: personas table

Revision ID: cdfed859bb1f
Revises: 942a643de71f
Create Date: 2026-06-05 20:55:33.673967

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdfed859bb1f"
down_revision: str | Sequence[str] | None = "942a643de71f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personas",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=40), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_builtin AND user_id IS NULL AND slug IS NOT NULL) "
            "OR (NOT is_builtin AND user_id IS NOT NULL AND slug IS NULL)",
            name="ck_personas_builtin_xor_custom",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_personas_user_id", "personas", ["user_id"], unique=False)
    op.create_index(
        "uq_personas_builtin_slug",
        "personas",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("is_builtin"),
    )
    op.create_index(
        "uq_personas_user_name",
        "personas",
        ["user_id", "name"],
        unique=True,
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_personas_user_name",
        table_name="personas",
        postgresql_where=sa.text("user_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_personas_builtin_slug", table_name="personas", postgresql_where=sa.text("is_builtin")
    )
    op.drop_index("ix_personas_user_id", table_name="personas")
    op.drop_table("personas")
    # ### end Alembic commands ###
