"""slice-07: graph nodes/edges/history tables

Revision ID: f00f87bef9f6
Revises: 242bbe6579ff
Create Date: 2026-06-03 21:02:02.037991

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f00f87bef9f6"
down_revision: str | Sequence[str] | None = "242bbe6579ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_graph_nodes_engagement_id", "graph_nodes", ["engagement_id"], unique=False)
    op.create_index(
        "ix_graph_nodes_engagement_live",
        "graph_nodes",
        ["engagement_id"],
        unique=False,
        postgresql_where=sa.text("deleted = false"),
    )
    op.create_table(
        "graph_edges",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=128), nullable=False),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_id"], ["graph_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["graph_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_graph_edges_engagement_id", "graph_edges", ["engagement_id"], unique=False)
    op.create_index("ix_graph_edges_source_id", "graph_edges", ["source_id"], unique=False)
    op.create_index("ix_graph_edges_target_id", "graph_edges", ["target_id"], unique=False)
    op.create_index(
        "uq_graph_edges_live_triple",
        "graph_edges",
        ["engagement_id", "source_id", "target_id", "relation"],
        unique=True,
        postgresql_where=sa.text("deleted = false"),
    )
    op.create_table(
        "graph_node_history",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("node_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=512), nullable=False),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["graph_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_graph_node_history_node_id",
        "graph_node_history",
        ["node_id", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    op.create_table(
        "graph_edge_history",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("edge_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=128), nullable=False),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["edge_id"], ["graph_edges.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_graph_edge_history_edge_id",
        "graph_edge_history",
        ["edge_id", sa.literal_column("recorded_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_graph_edge_history_edge_id", table_name="graph_edge_history")
    op.drop_table("graph_edge_history")
    op.drop_index("ix_graph_node_history_node_id", table_name="graph_node_history")
    op.drop_table("graph_node_history")
    op.drop_index(
        "uq_graph_edges_live_triple",
        table_name="graph_edges",
        postgresql_where=sa.text("deleted = false"),
    )
    op.drop_index("ix_graph_edges_target_id", table_name="graph_edges")
    op.drop_index("ix_graph_edges_source_id", table_name="graph_edges")
    op.drop_index("ix_graph_edges_engagement_id", table_name="graph_edges")
    op.drop_table("graph_edges")
    op.drop_index(
        "ix_graph_nodes_engagement_live",
        table_name="graph_nodes",
        postgresql_where=sa.text("deleted = false"),
    )
    op.drop_index("ix_graph_nodes_engagement_id", table_name="graph_nodes")
    op.drop_table("graph_nodes")
    # ### end Alembic commands ###
